# Copyright (c) 2021, salesforce.com, inc.
# All rights reserved.
# SPDX-License-Identifier: MIT
# For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/MIT
version: 2.1

executors:
  linux:
    working_directory: ~/lwc-dev-mobile-core
    docker:
      - image: circleci/node:lts

orbs:
  win: circleci/windows@2.2.0
  codecov: codecov/codecov@1.0.5

jobs:
  run-tests-linux:
    executor: linux
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Setup
          command: yarn install && yarn build
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/lwc-dev-mobile-core/node_modules
      - run: 
          name: Run Tests
          command: yarn test
      - codecov/upload:
          file: reports/coverage/*.json
          flags: frontend,backend
      - store_artifacts:
          path: reports/
      - store_test_results:
          path: reports/junit/
  run-tests-windows:
    executor: win/default
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Setup
          shell: bash.exe
          command: yarn install && yarn build
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/lwc-dev-mobile-core/node_modules
      - run: 
          name: Run Tests
          shell: bash.exe
          command: yarn test
      - store_artifacts:
          path: reports/
      - store_test_results:
          path: reports/junit/

workflows:
  version: 2
  pr-test:
    jobs:
      - run-tests-linux
      - run-tests-windows